### PR TITLE
Take back the totem timer with LibTotemInfo-1.0

### PR DESCRIPTION
**Pull request by SwimmingTiger**
I noticed that because Blizzard removed `GetTotemInfo ()`, the totem timer has been removed from `NugRunning`.

However, I have created A compatible implementation of `GetTotemInfo ()`, which can be used as a library. So we can bring the totem timer back to NugRunning.

### CODE REVIEW

**Comment by d87** [comment]
Thanks

**Comment by d87** [comment]
Did they leave PLAYER_TOTEM_UPDATE event btw?

**Comment by YihaoPeng** [comment]
Yes. My lib depends on `UNIT_SPELLCAST_SUCCEEDED` and `PLAYER_TOTEM_UPDATE`.

So I really don't understand why Blizzard wants to delete `GetTotemInfo ()`...

**Comment by d87** [comment]
It's not an issue now, but you probably need to make your own totem update event with CallbackHandler-1.0. Your library may not always be the first in order to handle event to update its state before other addons use it

**Comment by SwimmingTiger** [comment]
Thanks for your suggestions, I will make the change.

**Pull request merged**
